### PR TITLE
bump jenkins and plugin versions

### PR DESCRIPTION
**Pull request by wbwork**
Just checked what is the version jenkins is suggesting itself.

image

### CODE REVIEW

**Comment by patrickjahns** [comment]
Any particular updates that are currently needed?

**Comment by wbwork** [comment]
> Any particular updates that are currently needed?

No, just keeping up to date

**Comment by patrickjahns** [comment]
The prometheus plugin has a update - maybe we can get rid of the ridiculous amount of error messages when we upgrade that as well.

image

**Comment by renanqts** [comment]
@wbwork can we close it?

**Comment by wbwork** [comment]
yes, why should we downgrade? :D

**Pull request closed without merging**
